services:
  backend:
    build:
      context: .
      dockerfile: ITransitionTask5/Dockerfile
    ports:
      - "5007:8080"
    restart: unless-stopped

  blazor:
    build:
      context: .
      dockerfile: ITransitionTask5.Blazor/Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend